### ISSUE TITLE
Error when running preprocess/postprocess/train/evaluate/predict

### ISSUE THREAD

**Issue by xptree** [DS3Lab/RosENet#2]
Hi, I am running the six actions provided my RosENet, but I met the following problems:

1. preprocess: `RosENet/test_dataset/10gs/10gs_ligand.pdb is not a valid filename or a valid PDB identifier`. Detailed log is as follows:
```
2020-07-09 16:07:04,979 - pyrosetta.rosetta - INFO - Found rosetta database at: /home/jiezhong/anaconda3/envs/rosenet/lib/python3.7/site-packages/pyrosetta/database; using it....
2020-07-09 16:07:04,980 - pyrosetta.rosetta - INFO - PyRosetta-4 2020 [Rosetta PyRosetta4.conda.linux.cxx11thread.serialization.CentOS.python37.Release 2020.27+release.cd4c8de0d49b3a523091f756785370c2adf91ff4 2020-06-29T13:41:46] retrieved from: http://www.pyrosetta.org
(C) Copyright Rosetta Commons Member Institutions. Created in JHU by Sergey Lyskov and PyRosetta Team.
PyRosetta-4 2020 [Rosetta PyRosetta4.conda.linux.cxx11thread.serialization.CentOS.python37.Release 2020.27+release.cd4c8de0d49b3a523091f756785370c2adf91ff4 2020-06-29T13:41:46] retrieved from: http://www.pyrosetta.org
(C) Copyright Rosetta Commons Member Institutions. Created in JHU by Sergey Lyskov and PyRosetta Team.
##### 55
['preprocess', 'test_dataset']
@> 6695 atoms and 1 coordinate set(s) were parsed in 0.09s.
2020-07-09 16:07:05,346 - .prody - DEBUG - 6695 atoms and 1 coordinate set(s) were parsed in 0.09s.
@> 6695 atoms and 1 coordinate set(s) were parsed in 0.06s.
2020-07-09 16:07:05,408 - .prody - DEBUG - 6695 atoms and 1 coordinate set(s) were parsed in 0.06s.
('MakeComplexPDB', '10gs', 'start')
('MakeComplexPDB', '10gs', 'error', OSError('/home/jiezhong/dev/RosENet/test_dataset/10gs/10gs_ligand.pdb is not a valid filename or a valid PDB identifier.'))
('MakeComplexPDB', '10gs', 'start')
('MakeComplexPDB', '10gs', 'error', OSError('/home/jiezhong/dev/RosENet/test_dataset/10gs/10gs_ligand.pdb is not a valid filename or a valid PDB identifier.'))
core.init: {0} Checking for fconfig files in pwd and ./rosetta/flags
core.init: {0} Rosetta version: PyRosetta4.conda.linux.cxx11thread.serialization.CentOS.python37.Release r259 2020.27+release.cd4c8de cd4c8de0d49b3a523091f756785370c2adf91ff4 http://www.pyrosetta.org 2020-06-29T13:41:46
core.init: {0} command: PyRosetta -in:auto_setup_metals -database /home/jiezhong/anaconda3/envs/rosenet/lib/python3.7/site-packages/pyrosetta/database
basic.random.init_random_generator: {0} 'RNG device' seed mode, using '/dev/urandom', seed=-777599417 seed_offset=0 real_seed=-777599417 thread_index=0
basic.random.init_random_generator: {0} RandomGenerator:init: Normal mode, seed=-777599417 RG_type=mt19937
```

2. voxelize: no bugs.

3. postprocess:  `FileNotFoundError: [Errno 2] No such file or directory: '/home/jiezhong/dev/RosENet/test_dataset/_filter_exp_12_25'`, Detailed log is as follows:
```
2020-07-09 16:13:43,306 - pyrosetta.rosetta - INFO - Found rosetta database at: /home/jiezhong/anaconda3/envs/rosenet/lib/python3.7/site-packages/pyrosetta/database; using it....
2020-07-09 16:13:43,306 - pyrosetta.rosetta - INFO - PyRosetta-4 2020 [Rosetta PyRosetta4.conda.linux.cxx11thread.serialization.CentOS.python37.Release 2020.27+release.cd4c8de0d49b3a523091f756785370c2adf91ff4 2020-06-29T13:41:46] retrieved from: http://www.pyrosetta.org
(C) Copyright Rosetta Commons Member Institutions. Created in JHU by Sergey Lyskov and PyRosetta Team.
core.init: {0} Checking for fconfig files in pwd and ./rosetta/flags
core.init: {0} Rosetta version: PyRosetta4.conda.linux.cxx11thread.serialization.CentOS.python37.Release r259 2020.27+release.cd4c8de cd4c8de0d49b3a523091f756785370c2adf91ff4 http://www.pyrosetta.org 2020-06-29T13:41:46
core.init: {0} command: PyRosetta -in:auto_setup_metals -database /home/jiezhong/anaconda3/envs/rosenet/lib/python3.7/site-packages/pyrosetta/database
basic.random.init_random_generator: {0} 'RNG device' seed mode, using '/dev/urandom', seed=-545797564 seed_offset=0 real_seed=-545797564 thread_index=0
basic.random.init_random_generator: {0} RandomGenerator:init: Normal mode, seed=-545797564 RG_type=mt19937
PyRosetta-4 2020 [Rosetta PyRosetta4.conda.linux.cxx11thread.serialization.CentOS.python37.Release 2020.27+release.cd4c8de0d49b3a523091f756785370c2adf91ff4 2020-06-29T13:41:46] retrieved from: http://www.pyrosetta.org
(C) Copyright Rosetta Commons Member Institutions. Created in JHU by Sergey Lyskov and PyRosetta Team.
##### 55
['postprocess', 'test_dataset']
Traceback (most recent call last):
  File "/home/jiezhong/anaconda3/envs/rosenet/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/jiezhong/anaconda3/envs/rosenet/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jiezhong/dev/RosENet/RosENet/__main__.py", line 4, in <module>
    parse_arguments()
  File "/home/jiezhong/dev/RosENet/RosENet/clui.py", line 84, in parse_arguments
    postprocess(dataset)
  File "/home/jiezhong/dev/RosENet/RosENet/postprocessing/__init__.py", line 4, in postprocess
    generate_tfrecords(dataset_object)
  File "/home/jiezhong/dev/RosENet/RosENet/postprocessing/postprocessing.py", line 77, in generate_tfrecords
    files = dataset_object.images
  File "/home/jiezhong/dev/RosENet/RosENet/objects/dataset.py", line 32, in images
    return [x for x in (self.path/settings.options).iterdir()]
  File "/home/jiezhong/dev/RosENet/RosENet/objects/dataset.py", line 32, in <listcomp>
    return [x for x in (self.path/settings.options).iterdir()]
  File "/home/jiezhong/anaconda3/envs/rosenet/lib/python3.7/pathlib.py", line 1102, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [Errno 2] No such file or directory: '/home/jiezhong/dev/RosENet/test_dataset/_filter_exp_12_25'
```

4. train/evaluate/predict: `NameError: name 'channels' is not defined`. Take `train` for example:
```
2020-07-09 16:15:05,277 - pyrosetta.rosetta - INFO - Found rosetta database at: /home/jiezhong/anaconda3/envs/rosenet/lib/python3.7/site-packages/pyrosetta/database; using it....
2020-07-09 16:15:05,277 - pyrosetta.rosetta - INFO - PyRosetta-4 2020 [Rosetta PyRosetta4.conda.linux.cxx11thread.serialization.CentOS.python37.Release 2020.27+release.cd4c8de0d49b3a523091f756785370c2adf91ff4 2020-06-29T13:41:46] retrieved from: http://www.pyrosetta.org
(C) Copyright Rosetta Commons Member Institutions. Created in JHU by Sergey Lyskov and PyRosetta Team.
core.init: {0} Checking for fconfig files in pwd and ./rosetta/flags
core.init: {0} Rosetta version: PyRosetta4.conda.linux.cxx11thread.serialization.CentOS.python37.Release r259 2020.27+release.cd4c8de cd4c8de0d49b3a523091f756785370c2adf91ff4 http://www.pyrosetta.org 2020-06-29T13:41:46
core.init: {0} command: PyRosetta -in:auto_setup_metals -database /home/jiezhong/anaconda3/envs/rosenet/lib/python3.7/site-packages/pyrosetta/database
basic.random.init_random_generator: {0} 'RNG device' seed mode, using '/dev/urandom', seed=-1029830563 seed_offset=0 real_seed=-1029830563 thread_index=0
basic.random.init_random_generator: {0} RandomGenerator:init: Normal mode, seed=-1029830563 RG_type=mt19937
PyRosetta-4 2020 [Rosetta PyRosetta4.conda.linux.cxx11thread.serialization.CentOS.python37.Release 2020.27+release.cd4c8de0d49b3a523091f756785370c2adf91ff4 2020-06-29T13:41:46] retrieved from: http://www.pyrosetta.org
(C) Copyright Rosetta Commons Member Institutions. Created in JHU by Sergey Lyskov and PyRosetta Team.
##### 55
['train', 'train_dataset', 'validation_dataset', 'model.py', 'htmd_rosetta_electronegativity', '1000']
Traceback (most recent call last):
  File "/home/jiezhong/anaconda3/envs/rosenet/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/jiezhong/anaconda3/envs/rosenet/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jiezhong/dev/RosENet/RosENet/__main__.py", line 4, in <module>
    parse_arguments()
  File "/home/jiezhong/dev/RosENet/RosENet/clui.py", line 87, in parse_arguments
    train(dataset, other_dataset, network, seed, channels)
NameError: name 'channels' is not defined
```
I guess the following line should be `channels=...` instead of `hannels=...`
https://github.com/DS3Lab/RosENet/blob/27bee1a9867793d4c2d172e0afc21cdcd0b1e5de/RosENet/clui.py#L70
I met another error after fixing the `hannels` problems:
```
Traceback (most recent call last):
  File "/home/jiezhong/anaconda3/envs/rosenet/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/jiezhong/anaconda3/envs/rosenet/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jiezhong/dev/RosENet/RosENet/__main__.py", line 4, in <module>
    parse_arguments()
  File "/home/jiezhong/dev/RosENet/RosENet/clui.py", line 87, in parse_arguments
    train(dataset, other_dataset, network, seed, channels)
  File "/home/jiezhong/dev/RosENet/RosENet/network/network.py", line 26, in train
    model_train_object = model_object.train_object(dataset_train,channels,seed)
  File "/home/jiezhong/dev/RosENet/RosENet/objects/model.py", line 131, in train_object
    return _ModelTrain(self, dataset_object, channels, seed)
  File "/home/jiezhong/dev/RosENet/RosENet/objects/model.py", line 74, in __init__
    seed)
  File "/home/jiezhong/dev/RosENet/RosENet/objects/model.py", line 19, in __init__
    self.iterator = input_fn().make_initializable_iterator()
  File "/home/jiezhong/dev/RosENet/RosENet/network/input.py", line 111, in in_fn
    dataset = dataset.map(parse_fn(training,shape), settings.parallel_calls)
TypeError: parse_fn() takes 1 positional argument but 2 were given
```

**Comment by hhassan1** [comment]
Hi, thank you for reporting this issue.

Regarding the first three steps, I believe there may be a problem with your setup/the state of your dataset. I have not been able to reproduce your error. I am sure the third step (postprocess) is failing due to the pipeline failing in the first step (preprocess).

I would like to have more information about the first problem you experienced. Could you post exactly what is the location of your dataset and modules in your system? (the personal names of the path can be hidden/substituted). Also, could you post the content of your `constants.py` file?

**Comment by hhassan1** [comment]
I added the changes to fix the training and validation problems. Some of the parameters you used were only placeholders, and thus should be substituted with correct ones.

For example, instead of calling directly `python3 -m RosENet -- train train_dataset validation_dataset model.py "htmd_rosetta_electronegativity" 1000`, you are expected to give a valid path for `train_dataset`, `validation_dataset` and `model.py`.

One working example (assuming the previous preprocess-voxelization-postprocess steps have worked correctly) would be the following:

`python3 -m RosENet -- train test_dataset test_dataset "RosENet/models/resnet.py" "htmd_rosetta" 1234`

where the last number is the seed, which can be left out if wanting a random seed (not recommended for reproducibility).

Note that I use here `test_dataset` twice. In an actual run of the code, you would want to do the preprocess-voxelize-postprocess on two separate datasets (thus the `train_dataset` and `validation_dataset` of the example), and use the path of both of them in the respective order.

The same applies for `evaluate` and `predict`. We need the `train_dataset` path because the code stores the model under the training dataset folder. No actual training data is used in evaluation nor prediction.

I will update the README to reflect this. Still, I leave this issue open until your first problem is solved.

**Comment by xptree** [comment]
@hhassan1 Thanks for your reply. It seems that the problem is due to the mgl path

https://github.com/DS3Lab/RosENet/blob/89f520cee01df818e134809a57a986eee4d30cb8/RosENet/constants.py#L18

The preprocess of `10gs` example goes well after I set mgl path correctly.

I have another question, how long it takes to preprocess pdbbind v2016 dataset?

**Comment by hhassan1** [comment]
I am afraid I cannot give you a good estimate, as when I used to run the preprocessing, I had access to a decent computing cluster. I would say it should take around one day or two if I recall correctly.

By default it is set up to use the maximum number of available threads, but you should consider that Rosetta uses OpenBLAS which also spawns its own threads. I would suggest you try with a small dataset and see how it behaves.

**Comment by xptree** [comment]
@hhassan1 Thanks.
